import Head from "next/head";
import Link from "next/link";
import { ReactNode } from "react";

type props = {
  children: ReactNode;
};

const AdminLayout = (props: props) => {
  return (
    <div id="AdminLayout">
      <Head>
        <title>takuya Next-blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/earlyaccess/hannari.css"
          rel="stylesheet"
        ></link>
      </Head>
      <header>
        <Link href={"/"}>
          <a>
            <img className="logo" src="/images/logo2.png" alt="" />
          </a>
        </Link>
        <Link href={"/"}>
          <a>
            <div className="title">Next Blog</div>
          </a>
        </Link>
        <div className="headerText">administrator page</div>
      </header>
      <main>{props.children}</main>
      <footer>
        <img className="logo" src="/images/logo2.png" alt="" />
        <div className="title">Next-blog</div>
        <div className="btn">
          <Link href={"/"}>
            <button>user page</button>
          </Link>
        </div>
      </footer>
    </div>
  );
};

export default AdminLayout;
