import { format } from "date-fns";
import Head from "next/head";
import { ReactNode, useState } from "react";

type props = {
  children: ReactNode;
};

type PastArticle = {
  title: string;
  postDate: Date;
};

export const Layout = (props: props) => {
  const [pastArticleList, setPastArticleList] = useState<PastArticle[]>([
    {
      title: "サンプル過去記事",
      postDate: new Date(),
    },
    {
      title: "サンプル過去記事",
      postDate: new Date(),
    },
    {
      title: "サンプル過去記事",
      postDate: new Date(),
    },
    {
      title: "サンプル過去記事",
      postDate: new Date(),
    },
    {
      title: "サンプル過去記事",
      postDate: new Date(),
    },
    {
      title: "サンプル過去記事",
      postDate: new Date(),
    },
  ]);

  return (
    <div id="Layout">
      <Head>
        <title>takuya Next-blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/earlyaccess/hannari.css"
          rel="stylesheet"
        ></link>
      </Head>
      <header>
        <img className="logo" src="/images/logo2.png" alt="" />
        <div className="title">Next Blog</div>
        <div className="snsImages">
          <img className="sns" src="/images/github.jpg" alt="" />
          <img className="sns" src="/images/twitter.png" alt="" />
          <img className="sns" src="/images/instagram.jpg" alt="" />
        </div>
      </header>
      <div className="topImage">
        <div>NEXT BLOG</div>
        <img src="/images/topImage5.jpg" alt="" />
      </div>
      <main>
        <div className="children">{props.children}</div>
        <div className="profile">
          <div className="profileContents">
            <img src="/images/logo2.png" alt="" />
            <div className="profileText">
              <div className="kanjiName">野口拓也</div>
              <div className="romajiName">Takuya Noguchi</div>
              <div className="job">ITエンジニア</div>
            </div>
          </div>
          <div className="pastArticleList">
            <div className="pastArticleTitle">過去の投稿</div>
            <div className="pastArticles">
              {pastArticleList.map((pastArticle, index) => {
                const formatPostDate = format(
                  pastArticle.postDate,
                  "yyyy/MM/dd"
                );
                return (
                  <div className="pastArticle" key={index}>
                    <div>{pastArticle.title}</div>
                    <div>{formatPostDate}</div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </main>
      <footer>
        <img className="logo" src="/images/logo2.png" alt="" />
        <div className="title">Next-blog</div>
        <div className="btn">
          <button>administrator page</button>
        </div>
      </footer>
    </div>
  );
};
